-- StickerMatch — Seed catalog (504 records: 42 teams x 11 players + a text "Team Crest")
-- Run after 01_schema.sql. Mirrors stickers_seed.csv so you can swap it later.
--
-- Real, publicly-known players/countries used as an illustrative sample with
-- OUR OWN sequential numbering and confederation as the category. This is NOT a
-- copy of any official (e.g. Panini) checklist or its numbering — plain text
-- only, no logos/images/branding. Edit freely.

insert into public.stickers (number, player_name, team_text, category) values
  ('001', 'Rayan Aït-Nouri', 'Algeria', 'CAF'),
  ('002', 'Team Crest', 'Algeria', 'CAF'),
  ('003', 'Riyad Mahrez', 'Algeria', 'CAF'),
  ('004', 'Alexis Guendouz', 'Algeria', 'CAF'),
  ('005', 'Ramy Bensebaini', 'Algeria', 'CAF'),
  ('006', 'Youcef Atal', 'Algeria', 'CAF'),
  ('007', 'Aïssa Mandi', 'Algeria', 'CAF'),
  ('008', 'Nabil Bentaleb', 'Algeria', 'CAF'),
  ('009', 'Saïd Benrahma', 'Algeria', 'CAF'),
  ('010', 'Amine Gouiri', 'Algeria', 'CAF'),
  ('011', 'Mohamed Amoura', 'Algeria', 'CAF'),
  ('012', 'Baghdad Bounedjah', 'Algeria', 'CAF'),
  ('013', 'Julián Álvarez', 'Argentina', 'CONMEBOL'),
  ('014', 'Team Crest', 'Argentina', 'CONMEBOL'),
  ('015', 'Lionel Messi', 'Argentina', 'CONMEBOL'),
  ('016', 'Emiliano Martínez', 'Argentina', 'CONMEBOL'),
  ('017', 'Nahuel Molina', 'Argentina', 'CONMEBOL'),
  ('018', 'Cristian Romero', 'Argentina', 'CONMEBOL'),
  ('019', 'Nicolás Otamendi', 'Argentina', 'CONMEBOL'),
  ('020', 'Enzo Fernández', 'Argentina', 'CONMEBOL'),
  ('021', 'Alexis Mac Allister', 'Argentina', 'CONMEBOL'),
  ('022', 'Rodrigo De Paul', 'Argentina', 'CONMEBOL'),
  ('023', 'Giuliano Simeone', 'Argentina', 'CONMEBOL'),
  ('024', 'Lautaro Martínez', 'Argentina', 'CONMEBOL'),
  ('025', 'Harry Souttar', 'Australia', 'AFC'),
  ('026', 'Team Crest', 'Australia', 'AFC'),
  ('027', 'Mathew Ryan', 'Australia', 'AFC'),
  ('028', 'Alessandro Circati', 'Australia', 'AFC'),
  ('029', 'Jordan Bos', 'Australia', 'AFC'),
  ('030', 'Lewis Miller', 'Australia', 'AFC'),
  ('031', 'Milos Degenek', 'Australia', 'AFC'),
  ('032', 'Jackson Irvine', 'Australia', 'AFC'),
  ('033', 'Riley McGree', 'Australia', 'AFC'),
  ('034', 'Aiden O''Neill', 'Australia', 'AFC'),
  ('035', 'Connor Metcalfe', 'Australia', 'AFC'),
  ('036', 'Craig Goodwin', 'Australia', 'AFC'),
  ('037', 'Marko Arnautović', 'Austria', 'UEFA'),
  ('038', 'Team Crest', 'Austria', 'UEFA'),
  ('039', 'David Alaba', 'Austria', 'UEFA'),
  ('040', 'Alexander Schlager', 'Austria', 'UEFA'),
  ('041', 'Kevin Danso', 'Austria', 'UEFA'),
  ('042', 'Philipp Lienhart', 'Austria', 'UEFA'),
  ('043', 'Konrad Laimer', 'Austria', 'UEFA'),
  ('044', 'Nicolas Seiwald', 'Austria', 'UEFA'),
  ('045', 'Marcel Sabitzer', 'Austria', 'UEFA'),
  ('046', 'Florian Grillitsch', 'Austria', 'UEFA'),
  ('047', 'Christoph Baumgartner', 'Austria', 'UEFA'),
  ('048', 'Michael Gregoritsch', 'Austria', 'UEFA'),
  ('049', 'Youri Tielemans', 'Belgium', 'UEFA'),
  ('050', 'Team Crest', 'Belgium', 'UEFA'),
  ('051', 'Kevin De Bruyne', 'Belgium', 'UEFA'),
  ('052', 'Thibaut Courtois', 'Belgium', 'UEFA'),
  ('053', 'Arthur Theate', 'Belgium', 'UEFA'),
  ('054', 'Timothy Castagne', 'Belgium', 'UEFA'),
  ('055', 'Maxim De Cuyper', 'Belgium', 'UEFA'),
  ('056', 'Amadou Onana', 'Belgium', 'UEFA'),
  ('057', 'Jérémy Doku', 'Belgium', 'UEFA'),
  ('058', 'Charles De Ketelaere', 'Belgium', 'UEFA'),
  ('059', 'Leandro Trossard', 'Belgium', 'UEFA'),
  ('060', 'Romelu Lukaku', 'Belgium', 'UEFA'),
  ('061', 'Marquinhos', 'Brazil', 'CONMEBOL'),
  ('062', 'Team Crest', 'Brazil', 'CONMEBOL'),
  ('063', 'Vinicius Júnior', 'Brazil', 'CONMEBOL'),
  ('064', 'Alisson', 'Brazil', 'CONMEBOL'),
  ('065', 'Danilo', 'Brazil', 'CONMEBOL'),
  ('066', 'Éder Militão', 'Brazil', 'CONMEBOL'),
  ('067', 'Gabriel Magalhães', 'Brazil', 'CONMEBOL'),
  ('068', 'Casemiro', 'Brazil', 'CONMEBOL'),
  ('069', 'Bruno Guimarães', 'Brazil', 'CONMEBOL'),
  ('070', 'Rodrygo', 'Brazil', 'CONMEBOL'),
  ('071', 'Matheus Cunha', 'Brazil', 'CONMEBOL'),
  ('072', 'Raphinha', 'Brazil', 'CONMEBOL'),
  ('073', 'Jonathan David', 'Canada', 'CONCACAF'),
  ('074', 'Team Crest', 'Canada', 'CONCACAF'),
  ('075', 'Alphonso Davies', 'Canada', 'CONCACAF'),
  ('076', 'Dayne St. Clair', 'Canada', 'CONCACAF'),
  ('077', 'Richie Laryea', 'Canada', 'CONCACAF'),
  ('078', 'Derek Cornelius', 'Canada', 'CONCACAF'),
  ('079', 'Stephen Eustáquio', 'Canada', 'CONCACAF'),
  ('080', 'Ismaël Koné', 'Canada', 'CONCACAF'),
  ('081', 'Jonathan Osorio', 'Canada', 'CONCACAF'),
  ('082', 'Jacob Shaffelburg', 'Canada', 'CONCACAF'),
  ('083', 'Tajon Buchanan', 'Canada', 'CONCACAF'),
  ('084', 'Cyle Larin', 'Canada', 'CONCACAF'),
  ('085', 'Vozinha', 'Cape Verde', 'CAF'),
  ('086', 'Team Crest', 'Cape Verde', 'CAF'),
  ('087', 'Ryan Mendes', 'Cape Verde', 'CAF'),
  ('088', 'Logan Costa', 'Cape Verde', 'CAF'),
  ('089', 'Pico', 'Cape Verde', 'CAF'),
  ('090', 'Steven Moreira', 'Cape Verde', 'CAF'),
  ('091', 'João Paulo', 'Cape Verde', 'CAF'),
  ('092', 'Kevin Pina', 'Cape Verde', 'CAF'),
  ('093', 'Jamiro Monteiro', 'Cape Verde', 'CAF'),
  ('094', 'Vannick Semedo', 'Cape Verde', 'CAF'),
  ('095', 'Jovane Cabral', 'Cape Verde', 'CAF'),
  ('096', 'Dailon Livramento', 'Cape Verde', 'CAF'),
  ('097', 'Luis Díaz', 'Colombia', 'CONMEBOL'),
  ('098', 'Team Crest', 'Colombia', 'CONMEBOL'),
  ('099', 'James Rodríguez', 'Colombia', 'CONMEBOL'),
  ('100', 'Camilo Vargas', 'Colombia', 'CONMEBOL'),
  ('101', 'Dávinson Sánchez', 'Colombia', 'CONMEBOL'),
  ('102', 'Yerry Mina', 'Colombia', 'CONMEBOL'),
  ('103', 'Daniel Muñoz', 'Colombia', 'CONMEBOL'),
  ('104', 'Jefferson Lerma', 'Colombia', 'CONMEBOL'),
  ('105', 'Richard Ríos', 'Colombia', 'CONMEBOL'),
  ('106', 'Juan Fernando Quintero', 'Colombia', 'CONMEBOL'),
  ('107', 'Jhon Arias', 'Colombia', 'CONMEBOL'),
  ('108', 'Luis Suárez', 'Colombia', 'CONMEBOL'),
  ('109', 'Ivan Perišić', 'Croatia', 'UEFA'),
  ('110', 'Team Crest', 'Croatia', 'UEFA'),
  ('111', 'Luka Modrić', 'Croatia', 'UEFA'),
  ('112', 'Dominik Livaković', 'Croatia', 'UEFA'),
  ('113', 'Duje Ćaleta-Car', 'Croatia', 'UEFA'),
  ('114', 'Joško Gvardiol', 'Croatia', 'UEFA'),
  ('115', 'Josip Stanišić', 'Croatia', 'UEFA'),
  ('116', 'Mateo Kovačić', 'Croatia', 'UEFA'),
  ('117', 'Lovro Majer', 'Croatia', 'UEFA'),
  ('118', 'Mario Pašalić', 'Croatia', 'UEFA'),
  ('119', 'Ante Budimir', 'Croatia', 'UEFA'),
  ('120', 'Andrej Kramarić', 'Croatia', 'UEFA'),
  ('121', 'Juriën Gaari', 'Curacao', 'CONCACAF'),
  ('122', 'Team Crest', 'Curacao', 'CONCACAF'),
  ('123', 'Leandro Bacuna', 'Curacao', 'CONCACAF'),
  ('124', 'Eloy Room', 'Curacao', 'CONCACAF'),
  ('125', 'Sherel Floranus', 'Curacao', 'CONCACAF'),
  ('126', 'Roshon Van Eijma', 'Curacao', 'CONCACAF'),
  ('127', 'Armando Obispo', 'Curacao', 'CONCACAF'),
  ('128', 'Livano Comenencia', 'Curacao', 'CONCACAF'),
  ('129', 'Juninho Bacuna', 'Curacao', 'CONCACAF'),
  ('130', 'Kenji Gorré', 'Curacao', 'CONCACAF'),
  ('131', 'Sontje Hansen', 'Curacao', 'CONCACAF'),
  ('132', 'Jearl Margaritha', 'Curacao', 'CONCACAF'),
  ('133', 'Moisés Caicedo', 'Ecuador', 'CONMEBOL'),
  ('134', 'Team Crest', 'Ecuador', 'CONMEBOL'),
  ('135', 'Enner Valencia', 'Ecuador', 'CONMEBOL'),
  ('136', 'Hernán Galíndez', 'Ecuador', 'CONMEBOL'),
  ('137', 'Piero Hincapié', 'Ecuador', 'CONMEBOL'),
  ('138', 'Pervis Estupiñán', 'Ecuador', 'CONMEBOL'),
  ('139', 'Willian Pacho', 'Ecuador', 'CONMEBOL'),
  ('140', 'Ángelo Preciado', 'Ecuador', 'CONMEBOL'),
  ('141', 'Joel Ordóñez', 'Ecuador', 'CONMEBOL'),
  ('142', 'Alan Franco', 'Ecuador', 'CONMEBOL'),
  ('143', 'Gonzalo Plata', 'Ecuador', 'CONMEBOL'),
  ('144', 'Kevin Rodríguez', 'Ecuador', 'CONMEBOL'),
  ('145', 'Omar Marmoush', 'Egypt', 'CAF'),
  ('146', 'Team Crest', 'Egypt', 'CAF'),
  ('147', 'Mohamed Salah', 'Egypt', 'CAF'),
  ('148', 'Mohamed El Shenawy', 'Egypt', 'CAF'),
  ('149', 'Mohamed Hany', 'Egypt', 'CAF'),
  ('150', 'Mohamed Abdelmonem', 'Egypt', 'CAF'),
  ('151', 'Ramy Rabia', 'Egypt', 'CAF'),
  ('152', 'Marwan Attia', 'Egypt', 'CAF'),
  ('153', 'Zizo', 'Egypt', 'CAF'),
  ('154', 'Hamdy Fathy', 'Egypt', 'CAF'),
  ('155', 'Mostafa Mohamed', 'Egypt', 'CAF'),
  ('156', 'Trézéguet', 'Egypt', 'CAF'),
  ('157', 'Jude Bellingham', 'England', 'UEFA'),
  ('158', 'Team Crest', 'England', 'UEFA'),
  ('159', 'Harry Kane', 'England', 'UEFA'),
  ('160', 'Jordan Pickford', 'England', 'UEFA'),
  ('161', 'Reece James', 'England', 'UEFA'),
  ('162', 'John Stones', 'England', 'UEFA'),
  ('163', 'Declan Rice', 'England', 'UEFA'),
  ('164', 'Jordan Henderson', 'England', 'UEFA'),
  ('165', 'Phil Foden', 'England', 'UEFA'),
  ('166', 'Bukayo Saka', 'England', 'UEFA'),
  ('167', 'Cole Palmer', 'England', 'UEFA'),
  ('168', 'Marcus Rashford', 'England', 'UEFA'),
  ('169', 'Ousmane Dembélé', 'France', 'UEFA'),
  ('170', 'Team Crest', 'France', 'UEFA'),
  ('171', 'Kylian Mbappé', 'France', 'UEFA'),
  ('172', 'Mike Maignan', 'France', 'UEFA'),
  ('173', 'William Saliba', 'France', 'UEFA'),
  ('174', 'Jules Koundé', 'France', 'UEFA'),
  ('175', 'Théo Hernández', 'France', 'UEFA'),
  ('176', 'Aurélien Tchouaméni', 'France', 'UEFA'),
  ('177', 'Eduardo Camavinga', 'France', 'UEFA'),
  ('178', 'Bradley Barcola', 'France', 'UEFA'),
  ('179', 'Marcus Thuram', 'France', 'UEFA'),
  ('180', 'Randal Kolo Muani', 'France', 'UEFA'),
  ('181', 'Jamal Musiala', 'Germany', 'UEFA'),
  ('182', 'Team Crest', 'Germany', 'UEFA'),
  ('183', 'Joshua Kimmich', 'Germany', 'UEFA'),
  ('184', 'Marc-André ter Stegen', 'Germany', 'UEFA'),
  ('185', 'Antonio Rüdiger', 'Germany', 'UEFA'),
  ('186', 'Jonathan Tah', 'Germany', 'UEFA'),
  ('187', 'Felix Nmecha', 'Germany', 'UEFA'),
  ('188', 'Leon Goretzka', 'Germany', 'UEFA'),
  ('189', 'Florian Wirtz', 'Germany', 'UEFA'),
  ('190', 'Serge Gnabry', 'Germany', 'UEFA'),
  ('191', 'Kai Havertz', 'Germany', 'UEFA'),
  ('192', 'Leroy Sané', 'Germany', 'UEFA'),
  ('193', 'Thomas Partey', 'Ghana', 'CAF'),
  ('194', 'Team Crest', 'Ghana', 'CAF'),
  ('195', 'Mohammed Kudus', 'Ghana', 'CAF'),
  ('196', 'Lawrence Ati Zigi', 'Ghana', 'CAF'),
  ('197', 'Alidu Seidu', 'Ghana', 'CAF'),
  ('198', 'Alexander Djiku', 'Ghana', 'CAF'),
  ('199', 'Gideon Mensah', 'Ghana', 'CAF'),
  ('200', 'Caleb Yirenkyi', 'Ghana', 'CAF'),
  ('201', 'Abdul Issahaku Fatawu', 'Ghana', 'CAF'),
  ('202', 'Kamal Deen Sulemana', 'Ghana', 'CAF'),
  ('203', 'Jordan Ayew', 'Ghana', 'CAF'),
  ('204', 'Antoine Semenyo', 'Ghana', 'CAF'),
  ('205', 'Frantzdy Pierrot', 'Haiti', 'CONCACAF'),
  ('206', 'Team Crest', 'Haiti', 'CONCACAF'),
  ('207', 'Duckens Nazon', 'Haiti', 'CONCACAF'),
  ('208', 'Johny Placide', 'Haiti', 'CONCACAF'),
  ('209', 'Ricardo Adé', 'Haiti', 'CONCACAF'),
  ('210', 'Carlens Arcus', 'Haiti', 'CONCACAF'),
  ('211', 'Hannes Delcroix', 'Haiti', 'CONCACAF'),
  ('212', 'Leverton Pierre', 'Haiti', 'CONCACAF'),
  ('213', 'Danley Jean Jacques', 'Haiti', 'CONCACAF'),
  ('214', 'Jean-Ricner Bellegarde', 'Haiti', 'CONCACAF'),
  ('215', 'Ruben Providence', 'Haiti', 'CONCACAF'),
  ('216', 'Don Deedson Louicius', 'Haiti', 'CONCACAF'),
  ('217', 'Mehdi Taremi', 'Iran', 'AFC'),
  ('218', 'Team Crest', 'Iran', 'AFC'),
  ('219', 'Sardar Azmoun', 'Iran', 'AFC'),
  ('220', 'Alireza Beiranvand', 'Iran', 'AFC'),
  ('221', 'Shoja Khalilzadeh', 'Iran', 'AFC'),
  ('222', 'Milad Mohammadi', 'Iran', 'AFC'),
  ('223', 'Ramin Rezaeian', 'Iran', 'AFC'),
  ('224', 'Hossein Kanaani', 'Iran', 'AFC'),
  ('225', 'Saeid Ezatolahi', 'Iran', 'AFC'),
  ('226', 'Saman Ghoddos', 'Iran', 'AFC'),
  ('227', 'Mohammad Mohebi', 'Iran', 'AFC'),
  ('228', 'Alireza Jahanbakhsh', 'Iran', 'AFC'),
  ('229', 'Franck Kessié', 'Ivory Coast', 'CAF'),
  ('230', 'Team Crest', 'Ivory Coast', 'CAF'),
  ('231', 'Sébastien Haller', 'Ivory Coast', 'CAF'),
  ('232', 'Yahia Fofana', 'Ivory Coast', 'CAF'),
  ('233', 'Ghislain Konan', 'Ivory Coast', 'CAF'),
  ('234', 'Odilon Kossounou', 'Ivory Coast', 'CAF'),
  ('235', 'Evan N''Dicka', 'Ivory Coast', 'CAF'),
  ('236', 'Wilfried Singo', 'Ivory Coast', 'CAF'),
  ('237', 'Ibrahim Sangaré', 'Ivory Coast', 'CAF'),
  ('238', 'Nicolas Pépé', 'Ivory Coast', 'CAF'),
  ('239', 'Simon Adingra', 'Ivory Coast', 'CAF'),
  ('240', 'Oumar Diakité', 'Ivory Coast', 'CAF'),
  ('241', 'Takumi Minamino', 'Japan', 'AFC'),
  ('242', 'Team Crest', 'Japan', 'AFC'),
  ('243', 'Takefusa Kubo', 'Japan', 'AFC'),
  ('244', 'Zion Suzuki', 'Japan', 'AFC'),
  ('245', 'Tsuyoshi Watanabe', 'Japan', 'AFC'),
  ('246', 'Kaishu Sano', 'Japan', 'AFC'),
  ('247', 'Ao Tanaka', 'Japan', 'AFC'),
  ('248', 'Daichi Kamada', 'Japan', 'AFC'),
  ('249', 'Ritsu Doan', 'Japan', 'AFC'),
  ('250', 'Keito Nakamura', 'Japan', 'AFC'),
  ('251', 'Shuto Machino', 'Japan', 'AFC'),
  ('252', 'Ayase Ueda', 'Japan', 'AFC'),
  ('253', 'Yazan Al-Naimat', 'Jordan', 'AFC'),
  ('254', 'Team Crest', 'Jordan', 'AFC'),
  ('255', 'Musa Al-Taamari', 'Jordan', 'AFC'),
  ('256', 'Yazeed Abulaila', 'Jordan', 'AFC'),
  ('257', 'Mohammad Abu Hashish', 'Jordan', 'AFC'),
  ('258', 'Yazan Al-Arab', 'Jordan', 'AFC'),
  ('259', 'Abdallah Nasib', 'Jordan', 'AFC'),
  ('260', 'Ibrahim Saadeh', 'Jordan', 'AFC'),
  ('261', 'Nizar Al-Rashdan', 'Jordan', 'AFC'),
  ('262', 'Noor Al-Rawabdeh', 'Jordan', 'AFC'),
  ('263', 'Mahmoud Al-Mardi', 'Jordan', 'AFC'),
  ('264', 'Ali Olwan', 'Jordan', 'AFC'),
  ('265', 'Minjae Kim', 'Korea Republic', 'AFC'),
  ('266', 'Team Crest', 'Korea Republic', 'AFC'),
  ('267', 'Heungmin Son', 'Korea Republic', 'AFC'),
  ('268', 'Hyeonwoo Jo', 'Korea Republic', 'AFC'),
  ('269', 'Youngwoo Seol', 'Korea Republic', 'AFC'),
  ('270', 'Yumin Cho', 'Korea Republic', 'AFC'),
  ('271', 'Taeseok Lee', 'Korea Republic', 'AFC'),
  ('272', 'Inbeom Hwang', 'Korea Republic', 'AFC'),
  ('273', 'Jaesung Lee', 'Korea Republic', 'AFC'),
  ('274', 'Kangin Lee', 'Korea Republic', 'AFC'),
  ('275', 'Hyeongyu Oh', 'Korea Republic', 'AFC'),
  ('276', 'Heechan Hwang', 'Korea Republic', 'AFC'),
  ('277', 'Edson Álvarez', 'Mexico', 'CONCACAF'),
  ('278', 'Team Crest', 'Mexico', 'CONCACAF'),
  ('279', 'Raúl Jiménez', 'Mexico', 'CONCACAF'),
  ('280', 'Luis Malagón', 'Mexico', 'CONCACAF'),
  ('281', 'Israel Reyes', 'Mexico', 'CONCACAF'),
  ('282', 'Johan Vásquez', 'Mexico', 'CONCACAF'),
  ('283', 'César Montes', 'Mexico', 'CONCACAF'),
  ('284', 'Jesús Gallardo', 'Mexico', 'CONCACAF'),
  ('285', 'Carlos Rodríguez', 'Mexico', 'CONCACAF'),
  ('286', 'Orbelín Pineda', 'Mexico', 'CONCACAF'),
  ('287', 'Hirving Lozano', 'Mexico', 'CONCACAF'),
  ('288', 'Santiago Giménez', 'Mexico', 'CONCACAF'),
  ('289', 'Youssef En-Nesyri', 'Morocco', 'CAF'),
  ('290', 'Team Crest', 'Morocco', 'CAF'),
  ('291', 'Achraf Hakimi', 'Morocco', 'CAF'),
  ('292', 'Yassine Bounou', 'Morocco', 'CAF'),
  ('293', 'Noussair Mazraoui', 'Morocco', 'CAF'),
  ('294', 'Nayef Aguerd', 'Morocco', 'CAF'),
  ('295', 'Sofyan Amrabat', 'Morocco', 'CAF'),
  ('296', 'Eliesse Ben Seghir', 'Morocco', 'CAF'),
  ('297', 'Ismael Saibari', 'Morocco', 'CAF'),
  ('298', 'Brahim Díaz', 'Morocco', 'CAF'),
  ('299', 'Abde Ezzalzouli', 'Morocco', 'CAF'),
  ('300', 'Ayoub El Kaabi', 'Morocco', 'CAF'),
  ('301', 'Memphis Depay', 'Netherlands', 'UEFA'),
  ('302', 'Team Crest', 'Netherlands', 'UEFA'),
  ('303', 'Virgil van Dijk', 'Netherlands', 'UEFA'),
  ('304', 'Bart Verbruggen', 'Netherlands', 'UEFA'),
  ('305', 'Nathan Aké', 'Netherlands', 'UEFA'),
  ('306', 'Jeremie Frimpong', 'Netherlands', 'UEFA'),
  ('307', 'Denzel Dumfries', 'Netherlands', 'UEFA'),
  ('308', 'Tijjani Reijnders', 'Netherlands', 'UEFA'),
  ('309', 'Ryan Gravenberch', 'Netherlands', 'UEFA'),
  ('310', 'Cody Gakpo', 'Netherlands', 'UEFA'),
  ('311', 'Donyell Malen', 'Netherlands', 'UEFA'),
  ('312', 'Wout Weghorst', 'Netherlands', 'UEFA'),
  ('313', 'Marko Stamenic', 'New Zealand', 'OFC'),
  ('314', 'Team Crest', 'New Zealand', 'OFC'),
  ('315', 'Chris Wood', 'New Zealand', 'OFC'),
  ('316', 'Max Crocombe', 'New Zealand', 'OFC'),
  ('317', 'Michael Boxall', 'New Zealand', 'OFC'),
  ('318', 'Liberato Cacace', 'New Zealand', 'OFC'),
  ('319', 'Tim Payne', 'New Zealand', 'OFC'),
  ('320', 'Finn Surman', 'New Zealand', 'OFC'),
  ('321', 'Joe Bell', 'New Zealand', 'OFC'),
  ('322', 'Sarpreet Singh', 'New Zealand', 'OFC'),
  ('323', 'Matt Garbett', 'New Zealand', 'OFC'),
  ('324', 'Elijah Just', 'New Zealand', 'OFC'),
  ('325', 'Martin Ødegaard', 'Norway', 'UEFA'),
  ('326', 'Team Crest', 'Norway', 'UEFA'),
  ('327', 'Erling Haaland', 'Norway', 'UEFA'),
  ('328', 'Ørjan Nyland', 'Norway', 'UEFA'),
  ('329', 'Julian Ryerson', 'Norway', 'UEFA'),
  ('330', 'Kristoffer Vassbakk Ajer', 'Norway', 'UEFA'),
  ('331', 'David Møller Wolfe', 'Norway', 'UEFA'),
  ('332', 'Sander Berge', 'Norway', 'UEFA'),
  ('333', 'Patrick Berg', 'Norway', 'UEFA'),
  ('334', 'Antonio Nusa', 'Norway', 'UEFA'),
  ('335', 'Oscar Bobb', 'Norway', 'UEFA'),
  ('336', 'Alexander Sørloth', 'Norway', 'UEFA'),
  ('337', 'Michael Amir Murillo', 'Panama', 'CONCACAF'),
  ('338', 'Team Crest', 'Panama', 'CONCACAF'),
  ('339', 'Aníbal Godoy', 'Panama', 'CONCACAF'),
  ('340', 'Orlando Mosquera', 'Panama', 'CONCACAF'),
  ('341', 'Andrés Andrade', 'Panama', 'CONCACAF'),
  ('342', 'Fidel Escobar', 'Panama', 'CONCACAF'),
  ('343', 'Cristian Martínez', 'Panama', 'CONCACAF'),
  ('344', 'Adalberto Carrasquilla', 'Panama', 'CONCACAF'),
  ('345', 'Édgar Bárcenas', 'Panama', 'CONCACAF'),
  ('346', 'José Fajardo', 'Panama', 'CONCACAF'),
  ('347', 'Ismael Díaz', 'Panama', 'CONCACAF'),
  ('348', 'José Luis Rodríguez', 'Panama', 'CONCACAF'),
  ('349', 'Gustavo Gómez', 'Paraguay', 'CONMEBOL'),
  ('350', 'Team Crest', 'Paraguay', 'CONMEBOL'),
  ('351', 'Miguel Almirón', 'Paraguay', 'CONMEBOL'),
  ('352', 'Roberto Fernández', 'Paraguay', 'CONMEBOL'),
  ('353', 'Juan José Cáceres', 'Paraguay', 'CONMEBOL'),
  ('354', 'Omar Alderete', 'Paraguay', 'CONMEBOL'),
  ('355', 'Júnior Alonso', 'Paraguay', 'CONMEBOL'),
  ('356', 'Andrés Cubas', 'Paraguay', 'CONMEBOL'),
  ('357', 'Mathías Villasanti', 'Paraguay', 'CONMEBOL'),
  ('358', 'Julio Enciso', 'Paraguay', 'CONMEBOL'),
  ('359', 'Ramón Sosa', 'Paraguay', 'CONMEBOL'),
  ('360', 'Antonio Sanabria', 'Paraguay', 'CONMEBOL'),
  ('361', 'Vitinha', 'Portugal', 'UEFA'),
  ('362', 'Team Crest', 'Portugal', 'UEFA'),
  ('363', 'Cristiano Ronaldo', 'Portugal', 'UEFA'),
  ('364', 'Diogo Costa', 'Portugal', 'UEFA'),
  ('365', 'Rúben Dias', 'Portugal', 'UEFA'),
  ('366', 'Nuno Mendes', 'Portugal', 'UEFA'),
  ('367', 'Bernardo Silva', 'Portugal', 'UEFA'),
  ('368', 'Bruno Fernandes', 'Portugal', 'UEFA'),
  ('369', 'Rúben Neves', 'Portugal', 'UEFA'),
  ('370', 'Francisco Conceição', 'Portugal', 'UEFA'),
  ('371', 'Pedro Neto', 'Portugal', 'UEFA'),
  ('372', 'Rafael Leão', 'Portugal', 'UEFA'),
  ('373', 'Almoez Ali', 'Qatar', 'AFC'),
  ('374', 'Team Crest', 'Qatar', 'AFC'),
  ('375', 'Hasan Al-Haydos', 'Qatar', 'AFC'),
  ('376', 'Meshaal Barsham', 'Qatar', 'AFC'),
  ('377', 'Boualem Khoukhi', 'Qatar', 'AFC'),
  ('378', 'Lucas Mendes', 'Qatar', 'AFC'),
  ('379', 'Pedro Miguel', 'Qatar', 'AFC'),
  ('380', 'Homam Al-Amin', 'Qatar', 'AFC'),
  ('381', 'Ahmed Fathi', 'Qatar', 'AFC'),
  ('382', 'Edmilson Junior', 'Qatar', 'AFC'),
  ('383', 'Ahmed Al-Ganehi', 'Qatar', 'AFC'),
  ('384', 'Akram Hassan Afif', 'Qatar', 'AFC'),
  ('385', 'Feras Albrikan', 'Saudi Arabia', 'AFC'),
  ('386', 'Team Crest', 'Saudi Arabia', 'AFC'),
  ('387', 'Salem Aldawsari', 'Saudi Arabia', 'AFC'),
  ('388', 'Nawaf Alaqidi', 'Saudi Arabia', 'AFC'),
  ('389', 'Hassan Altambakti', 'Saudi Arabia', 'AFC'),
  ('390', 'Jehad Thikri', 'Saudi Arabia', 'AFC'),
  ('391', 'Saud Abdulhamid', 'Saudi Arabia', 'AFC'),
  ('392', 'Nasser Aldawsari', 'Saudi Arabia', 'AFC'),
  ('393', 'Abdullah Alkhaybari', 'Saudi Arabia', 'AFC'),
  ('394', 'Musab Aljuwayr', 'Saudi Arabia', 'AFC'),
  ('395', 'Saleh Abu Alshamat', 'Saudi Arabia', 'AFC'),
  ('396', 'Saleh Alshehri', 'Saudi Arabia', 'AFC'),
  ('397', 'Scott McTominay', 'Scotland', 'UEFA'),
  ('398', 'Team Crest', 'Scotland', 'UEFA'),
  ('399', 'Andrew Robertson', 'Scotland', 'UEFA'),
  ('400', 'Angus Gunn', 'Scotland', 'UEFA'),
  ('401', 'Kieran Tierney', 'Scotland', 'UEFA'),
  ('402', 'Grant Hanley', 'Scotland', 'UEFA'),
  ('403', 'Billy Gilmour', 'Scotland', 'UEFA'),
  ('404', 'Lewis Ferguson', 'Scotland', 'UEFA'),
  ('405', 'Ryan Christie', 'Scotland', 'UEFA'),
  ('406', 'John McGinn', 'Scotland', 'UEFA'),
  ('407', 'Ben Gannon-Doak', 'Scotland', 'UEFA'),
  ('408', 'Ché Adams', 'Scotland', 'UEFA'),
  ('409', 'Kalidou Koulibaly', 'Senegal', 'CAF'),
  ('410', 'Team Crest', 'Senegal', 'CAF'),
  ('411', 'Sadio Mané', 'Senegal', 'CAF'),
  ('412', 'Edouard Mendy', 'Senegal', 'CAF'),
  ('413', 'Moussa Niakhaté', 'Senegal', 'CAF'),
  ('414', 'El Hadji Malick Diouf', 'Senegal', 'CAF'),
  ('415', 'Idrissa Gana Gueye', 'Senegal', 'CAF'),
  ('416', 'Pape Matar Sarr', 'Senegal', 'CAF'),
  ('417', 'Iliman Ndiaye', 'Senegal', 'CAF'),
  ('418', 'Krépin Diatta', 'Senegal', 'CAF'),
  ('419', 'Ismaïla Sarr', 'Senegal', 'CAF'),
  ('420', 'Nicolas Jackson', 'Senegal', 'CAF'),
  ('421', 'Lyle Foster', 'South Africa', 'CAF'),
  ('422', 'Team Crest', 'South Africa', 'CAF'),
  ('423', 'Ronwen Williams', 'South Africa', 'CAF'),
  ('424', 'Siyabonga Ngezana', 'South Africa', 'CAF'),
  ('425', 'Aubrey Modiba', 'South Africa', 'CAF'),
  ('426', 'Mbekezeli Mbokazi', 'South Africa', 'CAF'),
  ('427', 'Khuliso Mudau', 'South Africa', 'CAF'),
  ('428', 'Teboho Mokoena', 'South Africa', 'CAF'),
  ('429', 'Vaya Sithole', 'South Africa', 'CAF'),
  ('430', 'Themba Zwane', 'South Africa', 'CAF'),
  ('431', 'Oswin Appollis', 'South Africa', 'CAF'),
  ('432', 'Iqraam Rayners', 'South Africa', 'CAF'),
  ('433', 'Lamine Yamal', 'Spain', 'UEFA'),
  ('434', 'Team Crest', 'Spain', 'UEFA'),
  ('435', 'Rodri', 'Spain', 'UEFA'),
  ('436', 'Unai Simón', 'Spain', 'UEFA'),
  ('437', 'Robin Le Normand', 'Spain', 'UEFA'),
  ('438', 'Dean Huijsen', 'Spain', 'UEFA'),
  ('439', 'Marc Cucurella', 'Spain', 'UEFA'),
  ('440', 'Martín Zubimendi', 'Spain', 'UEFA'),
  ('441', 'Pedri', 'Spain', 'UEFA'),
  ('442', 'Fabián Ruiz', 'Spain', 'UEFA'),
  ('443', 'Nico Williams', 'Spain', 'UEFA'),
  ('444', 'Mikel Oyarzabal', 'Spain', 'UEFA'),
  ('445', 'Manuel Akanji', 'Switzerland', 'UEFA'),
  ('446', 'Team Crest', 'Switzerland', 'UEFA'),
  ('447', 'Granit Xhaka', 'Switzerland', 'UEFA'),
  ('448', 'Gregor Kobel', 'Switzerland', 'UEFA'),
  ('449', 'Nico Elvedi', 'Switzerland', 'UEFA'),
  ('450', 'Ricardo Rodríguez', 'Switzerland', 'UEFA'),
  ('451', 'Silvan Widmer', 'Switzerland', 'UEFA'),
  ('452', 'Denis Zakaria', 'Switzerland', 'UEFA'),
  ('453', 'Remo Freuler', 'Switzerland', 'UEFA'),
  ('454', 'Breel Embolo', 'Switzerland', 'UEFA'),
  ('455', 'Rubén Vargas', 'Switzerland', 'UEFA'),
  ('456', 'Dan Ndoye', 'Switzerland', 'UEFA'),
  ('457', 'Ferjani Sassi', 'Tunisia', 'CAF'),
  ('458', 'Team Crest', 'Tunisia', 'CAF'),
  ('459', 'Ellyes Skhiri', 'Tunisia', 'CAF'),
  ('460', 'Aymen Dahmen', 'Tunisia', 'CAF'),
  ('461', 'Montassar Talbi', 'Tunisia', 'CAF'),
  ('462', 'Yassine Meriah', 'Tunisia', 'CAF'),
  ('463', 'Ali Abdi', 'Tunisia', 'CAF'),
  ('464', 'Aïssa Laïdouni', 'Tunisia', 'CAF'),
  ('465', 'Hannibal Mejbri', 'Tunisia', 'CAF'),
  ('466', 'Naïm Sliti', 'Tunisia', 'CAF'),
  ('467', 'Elias Achouri', 'Tunisia', 'CAF'),
  ('468', 'Hazem Mastouri', 'Tunisia', 'CAF'),
  ('469', 'Weston McKennie', 'United States', 'CONCACAF'),
  ('470', 'Team Crest', 'United States', 'CONCACAF'),
  ('471', 'Christian Pulisic', 'United States', 'CONCACAF'),
  ('472', 'Matt Freese', 'United States', 'CONCACAF'),
  ('473', 'Chris Richards', 'United States', 'CONCACAF'),
  ('474', 'Tim Ream', 'United States', 'CONCACAF'),
  ('475', 'Antonee Robinson', 'United States', 'CONCACAF'),
  ('476', 'Tanner Tessmann', 'United States', 'CONCACAF'),
  ('477', 'Tyler Adams', 'United States', 'CONCACAF'),
  ('478', 'Timothy Weah', 'United States', 'CONCACAF'),
  ('479', 'Malik Tillman', 'United States', 'CONCACAF'),
  ('480', 'Folarin Balogun', 'United States', 'CONCACAF'),
  ('481', 'José María Giménez', 'Uruguay', 'CONMEBOL'),
  ('482', 'Team Crest', 'Uruguay', 'CONMEBOL'),
  ('483', 'Federico Valverde', 'Uruguay', 'CONMEBOL'),
  ('484', 'Sergio Rochet', 'Uruguay', 'CONMEBOL'),
  ('485', 'Ronald Araújo', 'Uruguay', 'CONMEBOL'),
  ('486', 'Sebastián Cáceres', 'Uruguay', 'CONMEBOL'),
  ('487', 'Mathías Olivera', 'Uruguay', 'CONMEBOL'),
  ('488', 'Nahitan Nández', 'Uruguay', 'CONMEBOL'),
  ('489', 'Rodrigo Bentancur', 'Uruguay', 'CONMEBOL'),
  ('490', 'Manuel Ugarte', 'Uruguay', 'CONMEBOL'),
  ('491', 'Facundo Pellistri', 'Uruguay', 'CONMEBOL'),
  ('492', 'Darwin Núñez', 'Uruguay', 'CONMEBOL'),
  ('493', 'Abdukodir Khusanov', 'Uzbekistan', 'AFC'),
  ('494', 'Team Crest', 'Uzbekistan', 'AFC'),
  ('495', 'Eldor Shomurodov', 'Uzbekistan', 'AFC'),
  ('496', 'Utkir Yusupov', 'Uzbekistan', 'AFC'),
  ('497', 'Farrukh Sayfiyev', 'Uzbekistan', 'AFC'),
  ('498', 'Sherzod Nasrullaev', 'Uzbekistan', 'AFC'),
  ('499', 'Husniddin Aliqulov', 'Uzbekistan', 'AFC'),
  ('500', 'Rustam Ashurmatov', 'Uzbekistan', 'AFC'),
  ('501', 'Khojiakbar Alijonov', 'Uzbekistan', 'AFC'),
  ('502', 'Odiljon Hamrobekov', 'Uzbekistan', 'AFC'),
  ('503', 'Otabek Shukurov', 'Uzbekistan', 'AFC'),
  ('504', 'Abbosbek Fayzullaev', 'Uzbekistan', 'AFC')
on conflict (number) do nothing;
